command:
- ${env}
- python3
- ${program}
- ${args}
method: bayes
metric:
  goal: maximize
  name: val_accuracy
name: resnet
parameters:
  Trainer.total_steps:
    values: [15000,30000,45000,60000]
  resnet.filters_num:
    distribution: int_uniform
    max: 16
    min: 4
  resnet.fc_units:
    distribution: int_uniform
    max: 64
    min: 8
  resnet.dropout_rate:
    distribution: uniform
    max: 0.5
    min: 0.1
entity: dllabgroup20
program: tune_wandb.py
