command:
- ${env}
- python3
- ${program}
- ${args}
method: bayes
metric:
  goal: maximize
  name: val_accuracy
name: cnn_sweep_test
parameters:
  cnn_blueprint.base_filters:
    distribution: int_uniform
    max: 4
    min: 1
  cnn_blueprint.dense_units:
    distribution: int_uniform
    max: 64
    min: 8
  cnn_blueprint.dropout_rate:
    distribution: uniform
    max: 0.5
    min: 0.1
  cnn_blueprint.n_blocks:
    distribution: int_uniform
    max: 3
    min: 2
  Trainer.total_steps:
    values: [15000, 30000, 45000, 60000]
entity: dllabgroup20
program: tune_wandb.py
