command:
- ${env}
- python3
- ${program}
- ${args}
method: bayes
metric:
  goal: maximize
  name: max_val_acc
name: team20_cnn_01
parameters:
  Trainer.total_steps:
    values: [7500, 10000, 15000, 20000]
  team20_cnn_01.filters:
    values: [[32,48,64], [8,16,32], [4,32,64], [16,64,256], [16,64,128],[48,128,256]]
  team20_cnn_01.kernel_size:
    values: [[5,3,3,3], [5,5,5,5], [3,3,3,3], [7,5,3,3], [7,5,5,3], [7,7,7,7]]
  team20_cnn_01.max_pool_dimension:
    values: [2,3]
  team20_cnn_01.strides:
    values: [1,2]
  team20_cnn_01.dropout_rate:
    distribution: uniform
    max: 0.5
    min: 0.1
entity: dllabgroup20
program: tune_wandb.py
