command:
- ${env}
- python3
- ${program}
- ${args}
method: bayes
metric:
  goal: maximize
  name: max_val_acc
name: xception
parameters:
  Trainer.total_steps:
    values: [2000,3000,4000]
  transfer_model.dense_units:
    distribution: int_uniform
    max: 32
    min: 8
  transfer_model.dropout_rate:
    distribution: uniform
    max: 0.5
    min: 0.1
  transfer_model.layer_num:
    distribution: int_uniform
    max: 20
    min: 12
entity: dllabgroup20
program: tune_wandb.py
